### ISSUE TITLE
Carbon intensity for day rates and targets

### ISSUE THREAD

**Issue by bigbrobrody** [BottlecapDave/HomeAssistant-CarbonIntensity#13]
### Describe the bug

Mismatch in carbon intensity values between day rates and target times attribute of a target.

### Reproduction steps

Plot current and next day rates on the same apex chart as targets, as follows:

type: custom:apexcharts-card
graph_span: 2d
now:
  show: true
all_series_config:
  stroke_width: 1
span:
  start: day
apex_config:
  dataLabels:
    enabled: true
header:
  show: true
  title: Carbon Intensity
  show_states: false
  colorize_states: true
series:
  - entity: event.carbon_intensity_north_west_england_current_day_rates
    data_generator: |
      return entity.attributes.rates.map((entry) => {
        return [entry.from, entry.intensity_forecast];
      });
    extend_to: false
    curve: stepline
    name: Today
  - entity: event.carbon_intensity_north_west_england_next_day_rates
    data_generator: |
      return entity.attributes.rates.map((entry) => {
        return [entry.from, entry.intensity_forecast];
      });
    curve: stepline
    name: Tomorrow
  - entity: binary_sensor.carbon_intensity_target_dishwasher
    data_generator: |
      return entity.attributes.target_times.map((entry) => {
        return [entry.from, entry.intensity_forecast];
      });
    type: area
    name: Dishwasher
  - entity: binary_sensor.carbon_intensity_target_ev_charging
    data_generator: |
      return entity.attributes.target_times.map((entry) => {
        return [entry.from, entry.intensity_forecast];
      });
    type: area
    name: EV

### Expected behaviour

Carbon intensity values match

### Integration Version

2.0.2

### Home Assistant Version

2024.4.3

### Fresh Install?

Not specified

### Home Assistant Logs

![Screenshot 2024-04-21 205741](https://github.com/BottlecapDave/HomeAssistant-CarbonIntensity/assets/14371302/5b5189a0-a99a-451d-ac41-c9eefc89944c)

The dishwasher target is for 2 hours between 23:30 and 05:30. The EV target is for 6 hours between the same times.

**Comment by bigbrobrody** [comment]
I think the discrepancy is down to changes in the forecast between when the day rates are captured and when the target is calculated. I guess this is potentially a feature rather than an issue.

**Comment by BottlecapDave** [comment]
Hello. Yeah this is by design. The target rate sensor does not recalculate the target rates times until they are all in the past and beyond desired time frame. This is so that the sensor does not come on beyond the required number of hours. 

For example if target times come on for the desired number of times, then the forecast is updated and the new lowest rates are within the time period but after the previous rates then it would turn on again.

**Comment by bigbrobrody** [comment]
I can see the logic in what you're saying.

However, if the target has start and end times would it make sense to recalculate every time new Carbon Intensity figures are received between the end time and start time (i.e the period when there will be no targets - in my example this would be the peak period from 5:30am to 11:30pm)?

If this makes any sense are you able to change the label from bug to feature request?

**Comment by BottlecapDave** [comment]
Yeah that is something that could be looked at improving, however I don't have an ETA on when that improvement would be made. The update would be

Recalculate target times if
- all current target times are in the past (existing behaviour) or
- applicable forecast times are in the future and the forecast has been updated (second check is to reduce unnecessary calculation)

**Comment by bigbrobrody** [comment]
Sounds eminently sensible. I wasn't expecting an ETA! Will take a look myself in a forked copy, if and when I can find the time.
